### ISSUE TITLE
IMS_ PER_ BATCH:

### ISSUE THREAD

**Issue by fengjingchehu1** [vidit09/geoshift#1]
hello,i want to aks a question.
In the last trainging -meaning teacher training,i wonder if IMS_ PER_ BATCH: Can 2 be changed to 1?
Looking forward to your reply。

**Comment by vidit09** [comment]
Hello,

Thanks for your interest in our work. Yes, you can change it to 1 but in all of our experiments, we used batch_size as mentioned in the respective yaml files. Additionally, you may have to increase the max iterations when batch size is lowered to 1.

**Comment by fengjingchehu1** [comment]
Thank you for your reply. To be honest, I am a first-year graduate student from China.
In this regard, I am a complete novice.Just now, I completed the training for the third step. I'm wondering if there are sentences similar to "python demo.py --config-file D:/learning/detectron2-main/configs/COCO-InstanceSegmentation/mask_rcnn_R_50_FPN_3x.yaml --input test5.jpg --opts MODEL.WEIGHTS detectron2://COCO-InstanceSegmentation/mask_rcnn_R_50_FPN_3x/137849600/model_final_f10217.pkl" that can be generated using the trained model.
This question might be basic, but I still look forward to your response.

**Comment by vidit09** [comment]
You can use `--eval-only` flag to the commands `python <train-filename> --eval-only --config-file <config-filename> MODEL.WEIGHTS <path to the weights> `. This command will start the evaluation of the test dataset. You can look into this and modify it to evaluate only one image.

**Comment by fengjingchehu1** [comment]
Thank you for your reply, and I wish you smooth work and good health!

**Comment by vidit09** [comment]
Thank you and same to you!
