### ISSUE TITLE
Figure5.ours

### ISSUE THREAD

**Issue by fengjingchehu** [vidit09/geoshift#2]
How can I obtain an image similar to the one labeled as "ours" in Figure 5 of your paper?

**Comment by vidit09** [comment]
Hello,

You can the output of this [line](https://github.com/vidit09/geoshift/blob/f1aafb78ce1d5ac7afef41ce778637820feadd99/mnist/sbmnist_rcnn.py#L202), which should have bounding boxes for the corresponding batch of images during evaluation.

**Comment by fengjingchehu** [comment]
i mean how can I use my own images to obtain visual results similar to Figure 5-ours?

**Comment by fengjingchehu** [comment]
I'm a first-year graduate student from China, and I'm a novice in this field. I'm eager to know how to use such trained model, for example, with my own images. I'm looking forward to your response!

**Comment by vidit09** [comment]
Hello,

Maybe how things are done [here](https://github.com/facebookresearch/detectron2/tree/main/demo). So, ideally, you need to load the image (check dataloader function) --> apply the preprocessing step(usually in __getitem__ function) --> load the trained model with weights( [example here](https://github.com/vidit09/geoshift/blob/f1aafb78ce1d5ac7afef41ce778637820feadd99/train_net_only_aggregator.py#L276) )--> call the model on the image (forward pass )--> post-process the image(example [here](https://github.com/vidit09/geoshift/blob/f1aafb78ce1d5ac7afef41ce778637820feadd99/mnist/sbmnist_rcnn.py#L202) ).

hope this helps.
